### ISSUE TITLE
A 1 sentence, 1 paragraph, 1 page description of: 

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot-sdk-docs#19]
- Polkadot
- Substrate
- FRAME 
- Cumulus

Idea from the Network State book.

**Comment by sacha-l** [comment]
Here's my take (from the from [this resource](https://polkadot-nfts-learning-hub.vercel.app/docs/background) I'm creating for use cases for non-fungibles on Polkadot):

> App-chains on Polkadot are built with [Substrate](https://docs.substrate.io) &mdash; a blockchain SDK built in Rust. More colloquially called Parachains, they contain custom low-level modules that when combined make up the overall business logic and services provided by the chain.

> Substrate has a framework to make it easy to create such modules, called [FRAME](https://github.com/paritytech/substrate/frame). 
You can think of it like this: Substrate is to FRAME as NodeJS is to React.💡

> In FRAME, these modules are referred to as **pallets** and the amalgamation of pallets (a.k.a the business logic of a chain) is referred to as the app-chain's **runtime**.

**Comment by kianenigma** [comment]
Substrate one is somewhat done in https://github.com/paritytech/substrate/pull/14581

**Comment by kianenigma** [comment]
Is being done as a part of https://github.com/paritytech/polkadot-sdk-docs/issues/25
