### ISSUE TITLE
Balances docs

### ISSUE THREAD

**Issue by juangirini** [paritytech/polkadot-sdk-docs#62]
Improve Balances pallet docs

**Comment by juangirini** [comment]
@liamaharon what is your improvement plan?

**Comment by liamaharon** [comment]
Primarily 
- Update docs with fungibles (it still only references Currency)
- Better document nuanced details like https://github.com/paritytech/polkadot-sdk/issues/1833#issuecomment-1805491978

**Comment by liamaharon** [comment]
Superseded by https://github.com/paritytech/polkadot-sdk-docs/issues/70
