### ISSUE TITLE
Finish up Templates document

### ISSUE THREAD

**Issue by juangirini** [paritytech/polkadot-sdk-docs#67]
In [docs/sdk/src/polkadot_sdk/templates.rs](https://github.com/paritytech/polkadot-sdk/blob/master/docs/sdk/src/polkadot_sdk/templates.rs)

### TODOs
- [ ] in general, we need to make a deliberate choice here of moving a few key templates to this repo (nothing stays in `substrate-developer-hub`) and the everything else should be community maintained.
- [ ] rename `substrate-node-template` to `substrate-basic-template`, `substrate-blockchain-template`. `node` is confusing in the name.  `substrate-blockchain-template` and `cumulus-parachain-template` go well together 🤝.

**Comment by NukeManDan** [comment]
Related to #26 - Looking at the template situation, the main tooling that is no longer maintained to update them on a polkadot release was https://github.com/paritytech/polkadot-sdk/blob/master/substrate/docs/node-template-release.md and the associated tooling https://github.com/paritytech/polkadot-sdk/blob/master/substrate/scripts/ci/node-template-release/src/main.rs that would need to be updated for the new SDK layout and CI, and I must be missing the companion CI for the cumulus parachain template.

https://github.com/paritytech/polkadot-sdk/issues/186 is related as well, perhaps https://forum.polkadot.network/t/r0gue-reimagining-polkadot-development-with-pop/4938#pop-3 should be consulted in what they want to take on/take over?
