### ISSUE TITLE
Tokens in Substrate Docs

### ISSUE THREAD

**Issue by juangirini** [paritytech/polkadot-sdk-docs#70]
This is a spin off of the Currency ref docs issue https://github.com/paritytech/polkadot-sdk-docs/issues/49 and its related PR https://github.com/paritytech/polkadot-sdk/pull/2683

## Tokens in Substrate Ref Doc

briefly explains 
- how Substrate follows the pattern of traits and trait implementation for tokens
- why this approach was chosen

### Fungible Traits and Pallets

list and compare fungible traits and pallets

### Non-fungible Traits and Pallets

list and compare non-fungible traits and pallets

## additionally

Improve and update trait and trait impl docs

**Comment by juangirini** [comment]
@liamaharon do you want to add something else?

**Comment by liamaharon** [comment]
> @liamaharon do you want to add something else?

yup will refine it. thanks!

**Comment by liamaharon** [comment]
Trait and trait impl docs also need improving. updated this issue to include improving/updating those docs.
